language: node_js
node_js:
  - "10"
  - "12"
  - "14"
git:
  clone: false
install:
  - git clone https://github.com/aversini/bump-and-release.git
  - cd bump-and-release
  - git branch -u origin/master
  - npm ci
