language: node_js
node_js:
  - "10"
  - "12"
  - "14"
git:
  depth: false
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags
  - git pull
  - npm ci
