on:
  push:
    tags:
    - 'v*'

- name: Git Release
  uses: anton-yurchenko/git-release@v3
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DRAFT_RELEASE: "false"
    PRE_RELEASE: "false"
    CHANGELOG_FILE: "CHANGELOG.md"
    ALLOW_EMPTY_CHANGELOG: "false"
    ALLOW_TAG_PREFIX: "true"
